### PR TITLE
Install redis/celery/flower

### PR DESCRIPTION
**Pull request by nbarnabee**
This PR addresses the first step of [T330633](https://phabricator.wikimedia.org/T330633)

### CODE REVIEW

**Comment by nbarnabee** [comment]
Redis, Celery and Flower are now installed, and `docker-compose up` will spin then up in their own containers.  They appear to be communicating with each other as expected.  I don't actually have them DOING anything yet; that will be the next PR.

**Comment by blancadesal** [comment]
> Redis, Celery and Flower are now installed, and `docker-compose up` will spin then up in their own containers. They appear to be communicating with each other as expected. I don't actually have them DOING anything yet; that will be the next PR.

Have you been able to manually test that everything works? e.g. declaring some dummy task inside app.py, then testing it works via the flask shell, that the task shows up in flower, etc.?

**Comment by nbarnabee** [comment]
> > Redis, Celery and Flower are now installed, and `docker-compose up` will spin then up in their own containers. They appear to be communicating with each other as expected. I don't actually have them DOING anything yet; that will be the next PR.
> 
> Have you been able to manually test that everything works? e.g. declaring some dummy task inside app.py, then testing it works via the flask shell, that the task shows up in flower, etc.?

I copy/pasted the simple "divide" task from our old [flask-blueprint](https://github.com/blancadesal/flask-blueprint) repo and ran it.  It's not registered, so the task itself failed, but celery received it and it showed up in flower, etc.

**Review by blancadesal — CHANGES_REQUESTED** [review]
Nice job wiring this final piece up! TIL watchdog is deprecated. Comments inline on how to use watchfiles instead.

**Review by blancadesal — APPROVED** [review]
Looks good!

**Review by Damilare1 — APPROVED** [review]

**Pull request merged**
