### PR TITLE
Add contributions route

### PR DESCRIPTION
**Pull request by nbarnabee**
This is built on the back of #11 

It adds
```
/api/contributions/
/api/contributions/latest
/api/contributions/{user}
```
I also added a new directory to store the blueprints.

See [T327103](https://phabricator.wikimedia.org/T327103)

### CODE REVIEW

**Comment by Damilare1** [comment]
23 files feels like a lot to review in one go. Would it be possible to split this PR into smaller tasks?

**Comment by nbarnabee** [comment]
> 23 files feels like a lot to review in one go. Would it be possible to split this PR into smaller tasks?

The number is deceptive.  This branch is based on the one for #11 and includes all of those changes, too.  The only things new here are in commits [54b6a03](https://github.com/wikimedia/toolhunt/pull/12/commits/54b6a03b830b57dedef2ba6be6bb4dfaa7a3766b) and [73f326e](https://github.com/wikimedia/toolhunt/pull/12/commits/73f326e3e2d4107f845d7495aa47a83efcb8137f)

**Comment by Damilare1** [comment]
> > 23 files feels like a lot to review in one go. Would it be possible to split this PR into smaller tasks?
> 
> The number is deceptive. This branch is based on the one for #11 and includes all of those changes, too. The only things new here are in commits [54b6a03](https://github.com/wikimedia/toolhunt/pull/12/commits/54b6a03b830b57dedef2ba6be6bb4dfaa7a3766b) and [73f326e](https://github.com/wikimedia/toolhunt/pull/12/commits/73f326e3e2d4107f845d7495aa47a83efcb8137f)

oh ok, in that case let's have this PR target that branch instead of the main branch. So the content in this PR would be the diff between this and the last PR.

**Comment by nbarnabee** [comment]
> oh ok, in that case let's have this PR target that branch instead of the main branch. So the content in this PR would be the diff between this and the older branch.

Oh!  Oh, geez, I never thought about doing it that way.  That makes a lot more sense.

**Pull request closed without merging**
