### PR TITLE
Add, configure and run local CI

### PR DESCRIPTION
**Pull request by nbarnabee**
This PR addresses [T330128]( https://phabricator.wikimedia.org/T330128)

I've added local CI and run it.  This has resulted in changes to a lot of files, but it's all formatting.  The only remotely substantial change occurs in `routes.py` lines 159-161, which introduces better error handling.

### CODE REVIEW

**Comment by nbarnabee** [comment]
Downgrading this PR to draft while I work to add changes requested in [T330135](https://phabricator.wikimedia.org/T330135)

**Comment by nbarnabee** [comment]
[bcbc2fb](https://github.com/wikimedia/toolhunt/pull/37/commits/bcbc2fba69f11b1f83c46d42ed8b63e7572bcf52) addresses [T330135](https://phabricator.wikimedia.org/T330135).  It's a two-for-one deal!

**Review by blancadesal — APPROVED** [review]

**Comment by blancadesal** [comment]
Nice! 🎉 Could you add a paragraph to the README explaining how to run CI locally?

**Comment by nbarnabee** [comment]
> Nice! 🎉 Could you add a paragraph to the README explaining how to run CI locally?

Can do!

**Pull request merged**
