### PR TITLE
Build put route

### PR DESCRIPTION
**Pull request by nbarnabee**
Have added a throughput for PUT requests, passing data received from the frontend to Toolhub server.

### CODE REVIEW

**Comment by nbarnabee** [comment]
Now fully functional, will update our records upon a successful insertion to Toolhub.  I look forward to demo'ing this at our team meeting in half an hour.

**Comment by nbarnabee** [comment]
Another force push to deal with rebasing.  Side note:  `git reset` has changed my life.

**Comment by blancadesal** [comment]
To avoid major merge conflicts, I'm thinking it would probably be easiest to merge #PR29 first, then manually rebase this PR on top? What do you think @nbarnabee?

**Comment by nbarnabee** [comment]
> To avoid major merge conflicts, I'm thinking it would probably be easiest to merge #29 first, then manually rebase this PR on top? What do you think @nbarnabee?

I agree entirely!

**Comment by nbarnabee** [comment]
> > To avoid major merge conflicts, I'm thinking it would probably be easiest to merge #29 first, then manually rebase this PR on top? What do you think @nbarnabee?
> 
> I agree entirely!

And the same is probably true of #27

**Comment by nbarnabee** [comment]
Manually edited this to incorporate the massive restructuring changes.  This probably isn't working right now; I'll need to do more Oauth work following the various updates that have coupled the front- and backend.

**Comment by nbarnabee** [comment]
To my utter astonishment, this still works perfectly and is ready for review.

To test, run both the front and backend containers, and, from the toolhunt directory, upgrade and insert the mock data:
```
docker-compose exec flask-web python manage.py insert_fields
docker-compose exec flask-web python manage.py insert_mock_data
```
Go to `localhost:8082/api/login` and follow the authentication route, then to `localhost:8082/api/documentation`

I've pared the mock data down to just what I need to test this route, as it all gets completely changed by #30 anyway.  
There should only be two tasks in the task table, and you can check them by making a GET request to /api/tasks
By making PUT requests to /api/tasks/{id} you can play around with the various responses given if a task doesn't exist, or has already been completed, or if the request body doesn't match the given task, etc. 

You can get "success" results by entering the following request along with the correct task id.
```
{
"tool": "testy-mc-test-tool",
"value": "https://www.example.com",
"field": "bugtracker_url"
}
```
Then you can check the demo server audit logs to see the result:  https://toolhub-demo.wmcloud.org/api-docs#get-/api/auditlogs/

**Comment by blancadesal** [comment]
Recheck

**Comment by nbarnabee** [comment]
Force pushed rebase from main.

**Review by HWaruguru — APPROVED** [review]
Works well

**Comment by nbarnabee** [comment]
Now that the new mock data has been incorporated, my testing instructions above are out-of-date.  Follow the db population instructions given in the README, which will produce plenty of sample incomplete tasks that you can test.

**Comment by nbarnabee** [comment]
[624a048](https://github.com/wikimedia/toolhunt/pull/24/commits/624a04832cbd3daf222cbf35603f960b5d55251d) and [2797427](https://github.com/wikimedia/toolhunt/pull/24/commits/27974273263052992fd6ff527f945bdc181002be) address changes suggested by @Damilare1 

The main PUT route could definitely use some refactoring and better error handling.  Once #31 is merged I will move many (most?  all??) of these functions to ToolhubClient

**Review by Damilare1 — APPROVED** [review]
Thanks for working on this. LGTM!

**Pull request merged**
