### PR TITLE
Build metrics routes

### PR DESCRIPTION
**Pull request by nbarnabee**
This PR addresses [T324674](https://phabricator.wikimedia.org/T324674)

### CODE REVIEW

**Comment by nbarnabee** [comment]
GET requests to the various /api/metrics endpoints will now return arrays of objects, with each object containing the description of the metric (e.g., "Number of tools in the database:") and the associated value.  On the frontend side, it should be extremely easy to generate information cards based on this data.

**Comment by nbarnabee** [comment]
I realized that my error handling was completely failing and have fixed it.

**Comment by blancadesal** [comment]
Could the metrics/user endpoint be folded into the metrics/contributions endpoint, passing the username as a query parameter?

**Comment by blancadesal** [comment]
> > Could the metrics/user endpoint be folded into the metrics/contributions endpoint, passing the username as a query parameter?
> I like that idea, for a future dashboard expansion, but I think I would want to make that a separate endpoint, since it would need to be tied to a form and should be displayed in its own place, without "total contributions" and "global contributions in the next 30 days".

Ok, let's leave things as they are for now!

**Review by blancadesal — APPROVED** [review]

**Pull request merged**
