### PR TITLE
Adopt GNU GPL3.0 license

### PR DESCRIPTION
**Pull request by nbarnabee**
After discussion, we have decided to switch from the MIT license to the GNU GPL 3.0

See [T324643](https://phabricator.wikimedia.org/T324643) for details.

### CODE REVIEW

**Review by HWaruguru — APPROVED** [review]
LGTM

**Comment by blancadesal** [comment]
From https://choosealicense.com/licenses/gpl-3.0/, "How to apply this license":

> Create a text file (typically named COPYING, as per GNU conventions) in the root of your source code and copy the text of the license into the file.

Let's follow conventions and rename the license file as suggested.

**Comment by nbarnabee** [comment]
> From https://choosealicense.com/licenses/gpl-3.0/, "How to apply this license":
> 
> > Create a text file (typically named COPYING, as per GNU conventions) in the root of your source code and copy the text of the license into the file.
> 
> Let's follow conventions and rename the license file as suggested.

Oh, interesting.  I admit I just used GitHub's "apply a license" template.  I'm surprised it didn't follow stated conventions.

**Comment by nbarnabee** [comment]
The file name has been changed as requested.

**Review by blancadesal — APPROVED** [review]

**Pull request merged**
