### PR TITLE
Improve mock data

### PR DESCRIPTION
**Pull request by nbarnabee**
This PR addresses [T329624](https://phabricator.wikimedia.org/T329624).  

It is dependent upon #29

### CODE REVIEW

**Comment by nbarnabee** [comment]
The mock data has now been converted to json and dramatically improved.  In its new form, I can use it to test my insertion functions and check that all of the API returns are functioning properly.

From the updated README:

> The mock data set contains three tools and a set of completed tasks. When run, the function `populate_db_test` will put the tools through the insertion process and auto-generate tasks, as it would with "real" data.
> 
> The results will appear on the command line. This command may be run multiple times; observe the command line messages to see what changes when a tool and/or task is already present in the DB.
> 
> The set of completed tasks will allow us to test that the high scores, user contributions, and latest contributions are returning correctly.

**Comment by nbarnabee** [comment]
Force pushed rebase from main

**Comment by blancadesal** [comment]
> The mock data has now been converted to json and dramatically improved. 

_Dramatically_ is the keyword here! 💯 🚀

**Review by blancadesal — APPROVED** [review]
LGTM! A huge improvement over the latest version.

**Pull request merged**
