### PR TITLE
Add GitHub pre-commit actions

### PR DESCRIPTION
**Pull request by nbarnabee**
Handling tox.  I have basically just copied this from https://github.com/mediawiki-utilities/python-mwsql/blob/7f2470164107bc341b8c54602d8080fb7e8b8a9d/.github/workflows/test.yml , though I did remove testing for Python versions other than 3.9, since 3.9 is necessarily all that we'll be using.

Is there some way I can actually test this???

### CODE REVIEW

**Comment by nbarnabee** [comment]
Ok, it doesn't actually work.  I don't really understand the mechanism behind this and have no idea why it fails (but I'm inclined to blame poetry).  Sorry.

**Comment by nbarnabee** [comment]
It works!

**Review by blancadesal — APPROVED** [review]
Yay, nice!! 🚀 This also has the side effect of generating a gh actions-poetry-tox template that can be used in other projects :))

**Comment by nbarnabee** [comment]
> Yay, nice!! 🚀 This also has the side effect of generating a gh actions-poetry-tox template that can be used in other projects :))

Yeah, I'm definitely going to be copying it!!  📝

**Pull request merged**
