### PR TITLE
Fetch & insert Toolhub data

### PR DESCRIPTION
**Pull request by nbarnabee**
We can now populate the DB with _real_ data!

See the [updated README](https://github.com/wikimedia/toolhunt/pull/21/files) for how to make this work.  At the moment it can't handle special characters and crashes as soon as it encounters one, but before that happens we still end up with loads of information to work with.

### CODE REVIEW

**Comment by nbarnabee** [comment]
Error (for reference): 
```
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1366, "Incorrect string value: '\\xC4\\xB1s\\xC4\\xB1' for column `mydatabase`.`tool`.`title` at row 1")
[SQL: INSERT INTO tool (name, title, description, url) VALUES (%s, %s, %s, %s)]
[parameters: ('toolforge-superyetkin', 'Kaynak avcısı', 'Citation Hunt for Turkish Wikipedia', 'https://superyetkin.toolforge.org/kaynak_avcisi.php')]
```

**Comment by nbarnabee** [comment]
Force pushed following a rebase from main

**Comment by nbarnabee** [comment]
I seem to have solved the encoding issue by using .encode() on both the tool title and the tool description, both of which were found to contain occasional characters that made the database upset; as far as I can tell, this is because MariaDB defaults to latin1 encoding in some cases. I haven't been able to figure out how to get it to apply utf8mb4 consistently, but storing the information as byte objects rather than strings seems to be working and as far as I can tell SQLAlchemy is clever enough to decode things properly.

This got me as far as 1453 tools and 14717 tasks (for reference, when we're deciding between a full data dump update vs. trying to finesse recent edits, this took almost 3 and a half minutes), before I ran into the next encoding issue:

```
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='")
[SQL: SELECT tool.name, tool.title, tool.description, tool.url
FROM tool
WHERE tool.name = %s]
[parameters: ('toolforge-dīgerō',)]
```

So I converted the name column into a BLOB as well, which caused me some issues as it had previously been my primary key. This has necessitated adding a new id column to the tool table and for some reason it isn't working properly. The work continues...

**Comment by nbarnabee** [comment]
Another force push to keep up with changes on the main branch.

**Comment by nbarnabee** [comment]
Bryan warned me off of the idea of converting everything to BLOBs, and after more experimentation, I discovered that the real problem was that Alembic was not recognizing my attempts to set an explicit charset for encoding/decoding.  Once I wiped the old migrations and started from the beginning, everything worked as desired.

**Comment by blancadesal** [comment]
First of all, congratulations on making all this work! We now have another piece of the puzzle :) I'm tempted to merge this as is, then address needed changes as separate, more granular PRs, each detailed in a Phabricator task – what do you think @nbarnabee?

**Comment by nbarnabee** [comment]
> First of all, congratulations on making all this work! We now have another piece of the puzzle :) I'm tempted to merge this as is, then address needed changes as separate, more granular PRs, each detailed in a Phabricator task – what do you think @nbarnabee?

Thanks!  I am completely happy to do it that way.

**Review by blancadesal — APPROVED** [review]

**Pull request merged**
